# This is a multi-stage Dockerfile (build and run)

# Remember to target specific version in your base image,
# because you want reproducibility (in a few years you will thank me)
FROM alpine:3.15 AS build

# The Hugo version
ARG VERSION=0.101.0
ARG SRC_URL=https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz

WORKDIR /hugo

RUN apk add curl gcc gcompat git npm && \
    npm install -g postcss postcss-cli autoprefixer && \
    curl -L ${SRC_URL} | tar -xz && \
    ls -la && \
    ./hugo version

# The source files are copied to /site
COPY . /site
WORKDIR /site

# And then we just run Hugo
RUN /hugo/hugo --minify --enableGitInfo

# stage 2
FROM nginx:1.23-alpine

WORKDIR /usr/share/nginx/html/

# Clean the default public folder
RUN rm -fr * .??*

# Finally, the "public" folder generated by Hugo in the previous stage
# is copied into the public fold of nginx
COPY --from=build /site/public /usr/share/nginx/html
